plugins: [
  discogs,
  web,
  embedart,
  convert,
  fetchart,
  play,
  replaygain,
  missing,
  mpdstats,
  smartplaylist,
  timedelta,
  itunescopy,
  lastgenre,
  duplicates,
  mbsync,
  git_annex,
  edit,
]

import:
  move: yes
  incremental: yes

library: ~/tunes/beets.db
directory: ~/tunes/
pluginpath:
  - ~/.config/beets/plugins

embedart:
  auto: yes

convert:
  dest: ~/Downloads

replaygain:
  overwrite: yes

smartplaylist:
  relative_to: ~/tunes
  playlist_dir: ~/.mpd/playlists
  playlists:
    - name: "1-added_this_week.m3u"
      album_query: added:@{1w}..
    - name: "2-added_this_month.m3u"
      album_query: added:@{1m}..

itunescopy:
  auto: yes
  dest: ~/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized

lastgenre:
  count: 3

duplicates:
  keys: [track, title, mb_albumid]

git_annex:
  directory: ~/tunes

edit:
  move: no

format_item: '$artist - $year-$month-$day - $album - $title'
format_album: '$albumartist - $year-$month-$day - $album'

replace:
  '[\\/]': _
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '\.$': _
  '\s+$': ''
  '^\s+': ''
  '\!': ''
