- include: homebrew.yml
- include: luarocks.yml
- include: python.yml

- file: src={{ item }} dest=~/Library/LaunchAgents/{{ item | basename }} state=link force=true
  with_items: launch_agents
  notify: load launchctl
