plugins: [
  discogs,
  web,
  embedart,
  convert,
  fetchart,
  play,
  # replaygain,
  missing,
  mpdstats,
  smartplaylist,
  itunescopy,
  lastgenre,
  duplicates,
  mbsync,
  edit,
]

import:
  move: yes
  incremental: yes
  incremental_skip_later: yes

library: /mnt/pool/tunes/beets.db
directory: /mnt/pool/tunes
pluginpath:
  - ~/.config/beets/plugins

embedart:
  auto: yes

convert:
  dest: ~/Downloads

replaygain:
  overwrite: yes

smartplaylist:
  relative_to: /mnt/pool/tunes
  playlist_dir: /mnt/pool/tunes
  playlists:
    - name: "added this week.m3u"
      album_query: 'added:-1w.. added-'
    - name: "added this month.m3u"
      album_query: 'added:-1m.. added-'
    - name: "alarm.m3u"
      query: 'alarm:true'
    - name: "grinch.m3u"
      query: 'grinch:true'

itunescopy:
  auto: yes
  dest: /mnt/pool/toitunes

lastgenre:
  count: 3

duplicates:
  keys: [track, title, mb_albumid]

git_annex:
  directory: ~/tunes

edit:
  move: no

format_item: '$artist - $year-$month-$day - $album - $track/$tracktotal - $title - $dj'
format_album: '$albumartist - $year-$month-$day - $album'

asciify_paths: true
replace:
  '[\\/]': _
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '\.$': _
  '\s+$': ''
  '^\s+': ''
  '\!': ''
