---
- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim

- name: install tpm
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm
